# Generated by Django 4.0.1 on 2023-02-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='totalQueryQuestion',
            field=models.IntegerField(default=0),
        ),
    ]
