# Generated by Django 4.0.1 on 2023-05-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_totalqueryquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='openAIToken',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
