# Generated by Django 4.0.1 on 2022-01-29 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bertConnector', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
