# Generated by Django 4.0.1 on 2023-02-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bertConnector', '0002_questioncounthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncounthistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
