# Generated by Django 4.0.1 on 2023-02-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bertConnector', '0003_questioncounthistory_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentModel', models.CharField(choices=[('BERT', 'BERT'), ('USE', 'USE')], default='BERT', max_length=10)),
                ('currentFaissPath', models.CharField(default='./pickle_files/serializedIndex02', max_length=50)),
                ('isModelLoading', models.BooleanField(default=False)),
                ('isFaissLoading', models.BooleanField(default=False)),
                ('modelLoadingStatus', models.IntegerField(default=0)),
                ('faissLoadingStatus', models.IntegerField(default=0)),
                ('startTimeStampModel', models.DateTimeField(auto_now_add=True)),
                ('currentTimeStampModel', models.DateTimeField(auto_now_add=True)),
                ('startTimeStampFaiss', models.DateTimeField(auto_now_add=True)),
                ('currentTimeStampFaiss', models.DateTimeField(auto_now_add=True)),
                ('serverUpTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]