# Generated by Django 4.0.1 on 2022-01-29 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bertConnector', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id']},
        ),
    ]
