# Generated by Django 4.0.1 on 2023-02-22 10:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bertConnector', '0004_serverstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serverstatus',
            old_name='currentFaissPath',
            new_name='currentQuestionsPath',
        ),
        migrations.RenameField(
            model_name='serverstatus',
            old_name='isFaissLoading',
            new_name='isQuestionsUpdating',
        ),
        migrations.RenameField(
            model_name='serverstatus',
            old_name='faissLoadingStatus',
            new_name='questionsUpdatingStatus',
        ),
        migrations.RemoveField(
            model_name='serverstatus',
            name='currentTimeStampFaiss',
        ),
        migrations.RemoveField(
            model_name='serverstatus',
            name='startTimeStampFaiss',
        ),
        migrations.AddField(
            model_name='serverstatus',
            name='currentTimeStampQuestions',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 22, 10, 58, 14, 253865, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serverstatus',
            name='startTimeStampQuestions',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 22, 10, 58, 18, 261059, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serverstatus',
            name='currentTimeStampModel',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='serverstatus',
            name='serverUpTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='serverstatus',
            name='startTimeStampModel',
            field=models.DateTimeField(),
        ),
    ]
