# Generated by Django 4.0.1 on 2023-02-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bertConnector', '0005_rename_currentfaisspath_serverstatus_currentquestionspath_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverstatus',
            name='currentTimeStampModel',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serverstatus',
            name='currentTimeStampQuestions',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serverstatus',
            name='serverUpTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serverstatus',
            name='startTimeStampModel',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serverstatus',
            name='startTimeStampQuestions',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
