# Generated by Django 4.0.1 on 2023-01-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bertConnector', '0006_alter_question_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField()),
                ('date', models.DateField()),
                ('documentId', models.TextField(unique=True)),
                ('document', models.FileField(upload_to='')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
