# Generated by Django 4.0.1 on 2023-02-23 02:06

from django.db import migrations, models


def set_default_value(apps, schema_editor):
    MyModel = apps.get_model('bertConnector', 'ServerStatus')
    MyModel.objects.all().update(currentQuestionsPathUSE='./pickle_files/serializedIndex02')


class Migration(migrations.Migration):

    dependencies = [
        ('bertConnector', '0006_alter_serverstatus_currenttimestampmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ServerStatus',
            name='currentQuestionsPathUSE',
            field=models.CharField(max_length=50,default="./pickle_files/serializedIndex02"),
            preserve_default=False,
        ),
        migrations.RunPython(set_default_value),
    ]
