# Generated by Django 4.0.1 on 2023-01-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bertConnector', '0008_alter_uploaddocument_documentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddocument',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
