# Generated by Django 4.0.1 on 2023-03-08 02:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bertConnector', '0009_alter_serverstatus_currentquestionspath_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 3, 8, 2, 41, 17, 359632, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
