# Generated by Django 4.0.1 on 2023-03-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bertConnector', '0010_question_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverstatus',
            name='currentQuestionsPathUSE',
            field=models.CharField(default='./pickle_files/indexFiles/serializedIndex01USE', max_length=50, null=True),
        ),
    ]
