# Generated by Django 4.0.1 on 2023-01-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bertConnector', '0010_documentquestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploaddocument',
            name='document',
        ),
        migrations.AddField(
            model_name='uploaddocument',
            name='note',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
