# Generated by Django 4.0.1 on 2023-03-12 13:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bertConnector', '0011_alter_serverstatus_currentquestionspathuse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverstatus',
            name='currentQuestionsPathUSE',
        ),
        migrations.AddField(
            model_name='question',
            name='examinationType',
            field=models.TextField(default='Quora'),
        ),
        migrations.AddField(
            model_name='question',
            name='questionAskedDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 12, 13, 21, 54, 546662, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serverstatus',
            name='currentModel',
            field=models.CharField(choices=[('BERT', 'BERT')], default='BERT', max_length=10),
        ),
    ]
