# Generated by Django 4.0.1 on 2023-03-12 13:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bertConnector', '0013_alter_question_questionaskeddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='questionAskedDate',
        ),
        migrations.AddField(
            model_name='question',
            name='examYear',
            field=models.DateField(default=datetime.datetime(2023, 3, 12, 13, 55, 47, 586588, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
